using Content.Client.UserInterface.Controls;
using Content.Shared._Wega.Mining;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
// LP edit start
using System.Collections.Generic;
using System.Linq;
using Content.Shared._Wega.Mining.Components;
// LP edit end

namespace Content.Client._Wega.Mining;

[GenerateTypedNameReferences]
public sealed partial class MiningConsoleWindow : FancyWindow
{
    public Action? ToggleModePressed;
    // LP edit start
    public Action? ActivateAllPressed;
    public Action? DeactivateAllPressed;
    // LP edit end
    public Action? ToggleWithdrawPressed;
    public Action<NetEntity>? ToggleServerActivationPressed;
    public Action<NetEntity, int>? ServerStageChangePressed;
    public Action<int>? AllSetStagePressed;

    /// <summary>
    /// Dictionr to track existing server controls by NetEnt
    /// </summary>
    private readonly Dictionary<NetEntity, MiningServerControl> _serverControls = new(); // LP edit

    public MiningConsoleWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ToggleMode.OnPressed += _ => ToggleModePressed?.Invoke();
        // LP edit start
        ActivateAllButton.OnPressed += _ => ActivateAllPressed?.Invoke();
        DeactivateAllButton.OnPressed += _ => DeactivateAllPressed?.Invoke();
        // LP edit end
        WithdrawButton.OnPressed += _ => ToggleWithdrawPressed?.Invoke();
        AllStage1Button.OnPressed += _ => AllSetStagePressed?.Invoke(1);
        AllStage2Button.OnPressed += _ => AllSetStagePressed?.Invoke(2);
        AllStage3Button.OnPressed += _ => AllSetStagePressed?.Invoke(3);
    }

    public void UpdateState(MiningConsoleBoundInterfaceState state)
    {
        // LP edit start
        ModeLabel.Text = state.Mode == MiningMode.Credits
            ? Loc.GetString("mining-console-mode-credits")
            : Loc.GetString("mining-console-mode-research");
        CreditsLabel.Text = $"{state.Credits:F0}";
        ResearchLabel.Text = $"{state.ResearchPoints:F0}";
        EfficiencyLabel.Text = Loc.GetString("mining-console-efficiency-count", ("count", state.EnabledServersCount)); // LP edit

        var currentServerUids = new HashSet<NetEntity>();

        foreach (var server in state.Servers)
        {
            currentServerUids.Add(server.Uid);

            if (_serverControls.TryGetValue(server.Uid, out var existingControl))
            {
                existingControl.UpdateData(server);
            }
            else
            {
                var control = new MiningServerControl(server);
                control.OnTogglePower += (serverUid) => ToggleServerActivationPressed?.Invoke(serverUid);
                control.OnStageChange += (serverUid, delta) => ServerStageChangePressed?.Invoke(serverUid, delta);
                ServersList.AddChild(control);
                _serverControls[server.Uid] = control;
            }
        }

        var serversToRemove = _serverControls.Keys.Except(currentServerUids).ToList();

        foreach (var uid in serversToRemove)
        {
            if (_serverControls.TryGetValue(uid, out var control))
            {
                ServersList.RemoveChild(control);
                _serverControls.Remove(uid);
            }
        }
        // LP edit end
    }
}
