# Модули для боргов
- type: latheRecipePack
  id: LPPSecurityModuls
  recipes:
  - LPPBorgModuleSecurityWeapon
  - LPPBorgModuleSecurityLaserCarbine
  - LPPBorgModuleSecurityCriminologist

- type: latheRecipePack
  id: LPPSpaceForgeCMDHardsuits
  recipes:
  - ClothingHeadHelmetEVALarge
  - ClothingOuterHardsuitEVAPrisoner
  - ClothingOuterHardsuitCombatOfficer
  - ClothingOuterHardsuitSecurity
  - ClothingOuterHardsuitCombatMedical
  - ClothingOuterHardsuitCombatRiot
  - ClothingOuterHardsuitSecurityPilot
  - LPPClothingOuterHardsuitSecurityEng
  - ClothingOuterHardsuitBrigmedic
  - ClothingOuterHardsuitWarden
  - ClothingOuterHardsuitLuxury
  - LPPClothingOuterHardsuitRd
  - ClothingOuterHardsuitMedical
  - ClothingOuterHardsuitEngineeringWhite
  - ClothingOuterHardsuitSecurityRed
  - ClothingOuterHardsuitMaxim
  - ClothingOuterHardsuitCap
