using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using System.Numerics;
using Content.Client._White.UI.Buttons;
using Robust.Shared.Configuration;
using Content.Shared._White.CCVar;
using Robust.Client.UserInterface.Controls;
using Content.Client._LP.Reklama;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);

            //LP edit start
            var reklamaBtns = ReklamaControlManager.GetAdIcons();
            foreach (var proto in reklamaBtns)
            {
                ReklamaLineBox.AddChild(proto);
            }

            // wwdp custom ghost
            _cfg.OnValueChanged(WhiteCVars.CustomGhosts, OnFunSettingChanged, true);
            var CGMButton = new CustomGhostsMenuOpenButton() { SetSize = new Vector2(77, 66) };
            CGMButton.AddChild(new TextureRect()
            {
                TextureScale = new Vector2(2, 2),
                TexturePath = "/Textures/_White/Ghosts/buttonicon.png",
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center
            });
            CustomGhostsMenu.AddChild(CGMButton);
            CustomGhostsMenu.Visible = _cfg.GetCVar(WhiteCVars.CustomGhosts);
            //LP edit end
        }

        //LP edit start: wwdp custom ghost
        public void OnFunSettingChanged(bool value)
        {
            CustomGhostsMenu.Visible = value;
        }
        //LP edit end

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float)UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float)LeftSide.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
