using Content.Shared._NF.Research;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
// LP edit start
using Content.Client.Resources;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Shared.Utility;
// LP edit end

namespace Content.Client._NF.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyResearchConsoleItem : LayoutContainer
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IResourceCache _resCache = default!; // LP edit

    // Public fields
    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype, ResearchAvailability>? SelectAction;
    public ResearchAvailability Availability;

    // Some visuals - now using centralized color scheme
    public static readonly Color DefaultColor = ResearchColorScheme.UIColors.DefaultTechBackground;
    public static readonly Color DefaultBorderColor = ResearchColorScheme.UIColors.DefaultTechBorder;
    public static readonly Color DefaultHoveredColor = ResearchColorScheme.UIColors.DefaultTechHover;

    public Color BackgroundColor = DefaultColor;
    public Color SecondaryBackgroundColor = DefaultColor;
    public Color BorderColor = DefaultBorderColor;
    public Color HoveredColor = DefaultHoveredColor;
    public Color SecondaryHoveredColor = DefaultHoveredColor;
    public Color SelectedColor = DefaultHoveredColor;
    public Color SecondarySelectedColor = DefaultHoveredColor;

    // Selection state
    private bool _isSelected = false;
    public bool IsSelected
    {
        get => _isSelected;
        set
        {
            if (_isSelected == value)
                return;
            _isSelected = value;
            UpdateColor();
        }
    }

    // LP edit start
    private const string BaseSpritePath = "/Textures/_LP/Interface/Tech/";
    private const string SelectedSpritePath = "/Textures/_LP/Interface/Tech/select_tech/";

    private string GetSpriteNameForAvailability()
    {
        return Availability switch
        {
            ResearchAvailability.Researched => "tech_doctrine_available_item_bg.png",
            ResearchAvailability.Available => "tech_doctrine_available_item_bg_blue.png",
            ResearchAvailability.PrereqsMet => "tech_doctrine_available_item_bg_yellow.png",
            ResearchAvailability.Unavailable => "tech_doctrine_available_item_bg_red.png",
            _ => "tech_doctrine_available_item_bg.png" // Default
        };
    }
    // LP edit end

    public FancyResearchConsoleItem(TechnologyPrototype proto, SpriteSystem sprite, ResearchAvailability availability)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Availability = availability;
        Prototype = proto;

        // Get the primary discipline for background color
        var primaryDiscipline = _prototype.Index<TechDisciplinePrototype>(proto.Discipline);
        var primaryColor = primaryDiscipline.Color;

        // Check if there's a secondary discipline
        TechDisciplinePrototype? secondaryDiscipline = null;
        Color? secondaryColor = null;
        if (proto.SecondaryDiscipline.HasValue)
        {
            secondaryDiscipline = _prototype.Index<TechDisciplinePrototype>(proto.SecondaryDiscipline.Value);
            secondaryColor = secondaryDiscipline.Color;
        }

        ResearchDisplay.Texture = sprite.Frame0(proto.Icon);

        Button.OnPressed += Selected;
        Button.OnDrawModeChanged += UpdateColor;
        // LP edit start
        BorderColor = ResearchColorScheme.GetTechBorderColor(availability);

        var techBackgroundSprite = new StyleBoxTexture
        {
            Mode = StyleBoxTexture.StretchMode.Stretch
        };
        techBackgroundSprite.SetPatchMargin(StyleBox.Margin.All, 10);
        Panel.PanelOverride = techBackgroundSprite;
        // LP edit end

        UpdateColor();
    }

    // LP edit start
    private void UpdateColor()
    {
        if (Panel.PanelOverride is not StyleBoxTexture texturePanel)
            return;

        var basePath = IsSelected ? SelectedSpritePath : BaseSpritePath;
        var spriteName = GetSpriteNameForAvailability();

        texturePanel.Texture = _resCache.GetTexture(basePath + spriteName);

        if (Button.IsHovered && !IsSelected)
            texturePanel.Modulate = Color.LightBlue; // brighter blue - hover
        else
            texturePanel.Modulate = Color.White; // Normal
    }
    // LP edit end

    protected override void ExitedTree()
    {
        base.ExitedTree();

        Button.OnPressed -= Selected;
    }

    private void Selected(BaseButton.ButtonEventArgs args)
    {
        SelectAction?.Invoke(Prototype, Availability);
    }
}

public sealed class DrawButton : Button
{
    public event Action? OnDrawModeChanged;

    public DrawButton()
    {
    }

    protected override void DrawModeChanged()
    {
        OnDrawModeChanged?.Invoke();
    }
}
