using System;
using Content.Client.UserInterface.Controls;
using Content.Shared._LP.Mining.Components;
using Content.Shared._Wega.Mining.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Utility;

namespace Content.Client._LP.Mining.Components
{
    [GenerateTypedNameReferences]
    public sealed partial class MiningCircuitboardRepairControl : FancyWindow
    {
        public event Action? OnScan;

        public MiningCircuitboardRepairControl()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("mining-circuitboard-repair-status-not-scanned")));
        }

        public void UpdateState(MiningCircuitboardRepairBoundInterfaceState state)
        {
            if (!state.IsScanned)
            {
                StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("mining-circuitboard-repair-status-not-scanned")));
                StepsContainer.Children.Clear();
                return;
            }

            StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("mining-circuitboard-repair-status-scanned")));

            StepsContainer.Children.Clear();

            for (var i = 0; i < state.Steps.Count; i++)
            {
                var step = state.Steps[i];
                var message = $"{(i + 1)}. {Loc.GetString(step.Description)}";

                if (i < state.CurrentStep)
                {
                    message += " " + Loc.GetString("mining-circuitboard-repair-step-complete");
                }
                else if (i == state.CurrentStep)
                {
                    message += " " + Loc.GetString("mining-circuitboard-repair-step-current");
                }

                var stepLabel = new RichTextLabel
                {
                    StyleClasses = { "LabelSmall" }
                };
                stepLabel.SetMessage(FormattedMessage.FromMarkupPermissive(message));
                StepsContainer.Children.Add(stepLabel);
            }

            if (state.CurrentStep >= state.Steps.Count)
            {
                StatusLabel.SetMessage(FormattedMessage.FromMarkupPermissive(Loc.GetString("mining-circuitboard-repair-status-complete")));
            }
        }
    }
}
